del *.aux /f /s /q /a 
del *.bak /f /s /q /a 
del *.log /f /s /q /a 
del *.bbl /f /s /q /a 
del *.dvi /f /s /q /a
del *.blg /f /s /q /a 
del *.thm /f /s /q /a 
del *.toc /f /s /q /a 
del *.toe /f /s /q /a 
del *.lof /f /s /q /a 
del *.lot /f /s /q /a 
del *.out  /f /s /q /a 
del  *.fen /f /s /q /a 
del *.ten /f /s /q /a 
del *.gz /f /s /q /a 
del *.gz(busy) /f /s /q /a 
del *.synctex /f /s /q /a 
del *.loa /f /s /q /a 